@Library('jenkins-builds') _

String clusterName = (BRANCH_NAME == "master") ? 'production-ecs' : 'development-ecs'

pipeline {
  agent any
  stages{
    stage('Build'){
      steps {
        script{
          dockerBuild("${BUILD_NUMBER}", "", "{{cookiecutter.project_slug}}", "./compose/django/Dockerfile", ".")
        }
      }
    }
    stage('deploy'){
      when {expression { BRANCH_NAME ==~ /(master|staging)/ }}
      steps {
        script{
          ecrPush("${BUILD_NUMBER}", BRANCH_NAME, true)
        }
      }
    }
  }
}
